### PR TITLE
Performance knitr

### PR DESCRIPTION
**Pull request by nullsatz**
Port the Sweave performance vignette and required preliminary R code to a single knitr file. For the performance graphs, swap prof for profvis.

The matching section code ran too fast to profile so I multiplied the dataset rows for that particular section.

I ran this new vignette in RStudio successfully on its own, but I think it needs to be tested via building and installing the package. There might be options that need to be added to the package description files. I had to use bookdown instead of markdown to keep the in text references to figures.

I think we can figure out some options to pass the profvis calls to make the graphs more suitable to this particular document.

I'm sure the code and text could use some cleaning up. Right now it's all quite messy as a rough draft.

### CODE REVIEW

**Comment by nullsatz** [comment]
I fixed some problems by changing the VignetteEngine declaration inside performance.Rmd, by adding some suggested packages, and by cleaning up figure references and R code inside performance.Rmd.

**Comment by nullsatz** [comment]
All the checks are passing. Do y'all want me to remove the old performance vignette, directory, and associated scripts before we merge?

**Comment by josherrickson** [comment]
@benthestatistician Thoughts on excluding this from CRAN vignettes? The old version wasn't on CRAN, I think just because CRAN doesn't like Sweave (anymore?) as opposed to explicitly disallowing with .Rbuildignore. The main reason I bring it up is that we shouldn't need to add more suggests if we exclude it from CRAN.

@nullsatz if Ben is in agreement, then I'd remove the new Suggests, and add vignettes/performance to .Rbuildignore.

**Comment by benthestatistician** [comment]
Agreed; no need to ship to CRAN.  (It's a special goodie for those of us who are on the GitHub site.)

**Comment by nullsatz** [comment]
> @benthestatistician Thoughts on excluding this from CRAN vignettes? The old version wasn't on CRAN, I think just because CRAN doesn't like Sweave (anymore?) as opposed to explicitly disallowing with .Rbuildignore. The main reason I bring it up is that we shouldn't need to add more suggests if we exclude it from CRAN.
> 
> @nullsatz if Ben is in agreement, then I'd remove the new Suggests, and add vignettes/performance to .Rbuildignore.

Ok, I removed the new 'Suggests' entries and added vignettes/performance.Rmd to .Rbuildignore. All the tests appear to be passing. I think it's ready to merge.

**Review by josherrickson — APPROVED** [review]
Looks good to me.

**Pull request merged**
